name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with EKS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws eks update-kubeconfig --region  us-east-1 --name cw-cluster

      - name: Deploy to EKS
        run: |
          kubectl set image deployment/appointment-service appointment-service=${{ secrets.DOCKER_HUB_UN }}/appointment-service:${{ github.sha }}
          kubectl rollout status deployment/appointment-service: 
         
      
     
            